# Generated by Django 5.0.7 on 2024-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents')),
            ],
        ),
    ]
