# Generated by Django 5.0.7 on 2024-12-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao_sebastiao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tipos docs',
            },
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao_sebastiao.tipo_doc'),
        ),
    ]
